spring:
  application:
    name: schedule-service
  datasource:
    username: 'postgres2'
    url: jdbc:postgresql://customers-postgresdb.cx9fv45tjcrx.us-east-1.rds.amazonaws.com:5432/schedules
    password: 'postgres2'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
    flyway:
      url: jdbc:postgresql://customers-postgresdb.cx9fv45tjcrx.us-east-1.rds.amazonaws.com:5432/schedules
      user: 'postgres2'
      password: 'postgres2'
