package com.yazykov.sportbet.paymentservice.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "invoices")
public class Invoice {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String invoiceId;
    @DynamoDBAttribute
    private CreditCard creditCard;
    @DynamoDBAttribute
    private BigDecimal amount;
    @DynamoDBAttribute
    private Long customerId;
    @DynamoDBAttribute
    private LocalDateTime operationDateTime;
}
